{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e94408e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Scrapy settings for hardware_store_parser project\n",
    "#\n",
    "# For simplicity, this file contains only settings considered important or\n",
    "# commonly used. You can find more settings consulting the documentation:\n",
    "#\n",
    "#     https://docs.scrapy.org/en/latest/topics/settings.html\n",
    "#     https://docs.scrapy.org/en/latest/topics/downloader-middleware.html\n",
    "#     https://docs.scrapy.org/en/latest/topics/spider-middleware.html\n",
    "\n",
    "BOT_NAME = 'hardware_store_parser'\n",
    "\n",
    "SPIDER_MODULES = ['hardware_store_parser.spiders']\n",
    "NEWSPIDER_MODULE = 'hardware_store_parser.spiders'\n",
    "\n",
    "LOG_ENABLED = True\n",
    "LOG_LEVEL = \"DEBUG\"\n",
    "\n",
    "IMAGES_STORE = 'photos'\n",
    "\n",
    "# Crawl responsibly by identifying yourself (and your website) on the user-agent\n",
    "USER_AGENT = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36'\n",
    "\n",
    "# Obey robots.txt rules\n",
    "ROBOTSTXT_OBEY = False\n",
    "\n",
    "# Configure maximum concurrent requests performed by Scrapy (default: 16)\n",
    "CONCURRENT_REQUESTS = 8\n",
    "\n",
    "# Configure a delay for requests for the same website (default: 0)\n",
    "# See https://docs.scrapy.org/en/latest/topics/settings.html#download-delay\n",
    "# See also autothrottle settings and docs\n",
    "DOWNLOAD_DELAY = 1\n",
    "# The download delay setting will honor only one of:\n",
    "#CONCURRENT_REQUESTS_PER_DOMAIN = 16\n",
    "#CONCURRENT_REQUESTS_PER_IP = 16\n",
    "\n",
    "# Disable cookies (enabled by default)\n",
    "COOKIES_ENABLED = True\n",
    "\n",
    "# Disable Telnet Console (enabled by default)\n",
    "#TELNETCONSOLE_ENABLED = False\n",
    "\n",
    "# Override the default request headers:\n",
    "# DEFAULT_REQUEST_HEADERS = {\n",
    "#   'Accept': 'disp_react_aa=2; ggr-widget-test=1; rnd-blabla=RU; disp_delivery_ab=B; disp_abc_categories=A; _ym_uid=1663362721247643777; _ym_d=1663362721; _gcl_au=1.1.1830018411.1663362721; iap.uid=eb98146e8ff94e46894938fe3ad9d0bd; _regionID=34; lastConfirmedRegionID=34; tmr_lvid=23c32653f7fb0dd0f7dade9828405d8e; tmr_lvidTS=1663362722448; aplaut_distinct_id=9PmK6zICuPwP; _gaexp=GAX1.2.nXqPoCboQeq6kIs8HbpCBg.19326.3!Xi1sqcpVSR-nNyL5UiNZnQ.19323.x994!nlBequwkToCH1Nvg6DHtIw.19342.0; uxs_uid=35d9f900-3604-11ed-aa2f-675f2aca1265; cookie_accepted=true; user-geolocation=0%2C0; sawOPH=true; dtCookie=v_4_srv_2_sn_CB977B39DAD521C67FA3AE03BD9A3496_perc_26623_ol_1_app-3Ab82b63450c1d92de_0; GACookieStorage=GA1.2.310423551.1663362722; _ym_isad=2; _reactCheckout=true; _gid=GA1.2.246721982.1663622308; x-api-option=cce-292; _ga=GA1.2.310423551.1663362722; tmr_reqNum=96; qrator_jsr=1663624430.900.j5OAQLM9iO05iQh3-bo33rlurjcgbat53c3ismvlladilb0o4-00; _ga_Z72HLV7H6T=GS1.1.1663624430.5.0.1663624430.0.0.0; qrator_jsid=1663624430.900.j5OAQLM9iO05iQh3-bfhss65f6h19377gn5sjd46tq8pf97fu; qrator_ssid=1663624432.452.MLOBstmt9SjzjBfF-q4kb00canmivguab4tek7bqnccju1vtv',\n",
    "#   'Accept-Language': 'ru'\n",
    "# }\n",
    "\n",
    "# Enable or disable spider middlewares\n",
    "# See https://docs.scrapy.org/en/latest/topics/spider-middleware.html\n",
    "#SPIDER_MIDDLEWARES = {\n",
    "#    'hardware_store_parser.middlewares.HardwareStoreParserSpiderMiddleware': 543,\n",
    "#}\n",
    "\n",
    "# Enable or disable downloader middlewares\n",
    "# See https://docs.scrapy.org/en/latest/topics/downloader-middleware.html\n",
    "#DOWNLOADER_MIDDLEWARES = {\n",
    "#    'hardware_store_parser.middlewares.HardwareStoreParserDownloaderMiddleware': 543,\n",
    "#}\n",
    "\n",
    "# Enable or disable extensions\n",
    "# See https://docs.scrapy.org/en/latest/topics/extensions.html\n",
    "#EXTENSIONS = {\n",
    "#    'scrapy.extensions.telnet.TelnetConsole': None,\n",
    "#}\n",
    "\n",
    "# Configure item pipelines\n",
    "# See https://docs.scrapy.org/en/latest/topics/item-pipeline.html\n",
    "ITEM_PIPELINES = {\n",
    "   'hardware_store_parser.pipelines.HardwareStoreParserPipeline': 400,\n",
    "   'hardware_store_parser.pipelines.PhotosPipeline': 200\n",
    "}\n",
    "\n",
    "# Enable and configure the AutoThrottle extension (disabled by default)\n",
    "# See https://docs.scrapy.org/en/latest/topics/autothrottle.html\n",
    "#AUTOTHROTTLE_ENABLED = True\n",
    "# The initial download delay\n",
    "#AUTOTHROTTLE_START_DELAY = 5\n",
    "# The maximum download delay to be set in case of high latencies\n",
    "#AUTOTHROTTLE_MAX_DELAY = 60\n",
    "# The average number of requests Scrapy should be sending in parallel to\n",
    "# each remote server\n",
    "#AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0\n",
    "# Enable showing throttling stats for every response received:\n",
    "#AUTOTHROTTLE_DEBUG = False\n",
    "\n",
    "# Enable and configure HTTP caching (disabled by default)\n",
    "# See https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#httpcache-middleware-settings\n",
    "#HTTPCACHE_ENABLED = True\n",
    "#HTTPCACHE_EXPIRATION_SECS = 0\n",
    "#HTTPCACHE_DIR = 'httpcache'\n",
    "#HTTPCACHE_IGNORE_HTTP_CODES = []\n",
    "#HTTPCACHE_STORAGE = 'scrapy.extensions.httpcache.FilesystemCacheStorage'"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
